version: '3.8'
services:
  service-a:
    build:
      context: .
      dockerfile: Dockerfile.service-a
    ports:
      - "8080:8080"
  service-b:
    build:
      context: .
      dockerfile: Dockerfile.service-b
    ports:
      - "8081:8081"

